package main

const (
	_TAG_TEMPLATE_GRAPH_TITLE = "{{PANDORA:TITLE}}"
	_TAG_TEMPLATE_GRAPH_JS    = "{{PANDORA:JS}}"
	_TAG_TEMPLATE_GRAPH_CSS   = "{{PANDORA:CSS}}"
	_TAG_TEMPLATE_GRAPH_DATA  = "{{PANDORA:DATA}}"
)

const (
	_TAG_TEMPLATE_GRAPH_TYPE_NORMAL = iota
	_TAG_TEMPLATE_GRAPH_TYPE_TITLE
	_TAG_TEMPLATE_GRAPH_TYPE_JS
	_TAG_TEMPLATE_GRAPH_TYPE_CSS
	_TAG_TEMPLATE_GRAPH_TYPE_DATA
)

const (
	_COLOR_GRAPH_DEFAULT      = `#93bdf6`
	_COLOR_GRAPH_FONT_DEFAULT = `#000000`
	_COLOR_RED                = `#f74c31`
	_COLOR_YELLOW             = `#ebc735`
	_COLOR_LIGHT_GRAY         = `#cccccc`
)

const (
	_FONT_GRAPH_DEFAULT = 12
)
